config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :characters, except: [:destroy] do
    resources :bookings, except: [:index, :show, :destroy, :edit, :update]
  end
  get '/bookings/:id', to: "bookings#show", as: :booking
  delete '/bookings/:id/edit', to: "bookings#destroy", as: :delete_booking
  get '/my-bookings', to: "bookings#my_bookings"
  get '/my-characters', to: "characters#my_characters"
  delete '/my-characters/:id', to: "characters#destroy", as: :delete_character
  get '/host-bookings/:id', to: "bookings#host_booking"
  patch '/host-bookings/:id/:status/set-status', to: "bookings#set_status", as: :edit_status
  get '/host-bookings', to: "bookings#host_bookings"
  get 'bookings/:id/edit', to: "bookings#edit", as: :edit_booking
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :character
  validates :start_date, :end_date, presence: true
  validates :status, presence: true

  enum status: {
    Pending: 0,
    Confirmed: 1,
    Denied: 2
  }, _prefix: true
end

app/models/character.rb
class Character < ApplicationRecord
  has_many_attached :photos
  has_many :bookings, dependent: :destroy
  belongs_to :user
  validates :name, presence: true, uniqueness: true
  validates :price, :description, :category, :address, presence: true
  geocoded_by :address
  validates :category, presence: true, inclusion: { in: %w[Animation Animal Christmas Comedy Game Horror Superhero Princess Other] }
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_name_and_description,
    against: [ :name, :description ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :characters, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :host_bookings, through: :characters, source: :bookings

  #   enum status: {
  #   pending: 0,
  #   active: 1,
  #   archived: 2
  # }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show edit destroy]

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(params_booking)
    @booking.character = Character.find(params[:character_id])
    @booking.user = current_user
    @booking.status = 0
    if @booking.save!
      redirect_to booking_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def edit
  end

  def set_status
    @booking = Booking.find(params[:id])
    @booking.status = params[:status].to_i
    @booking.save!
    redirect_back_or_to '/', allow_other_host: false
  end

  def destroy
    @booking.destroy
    redirect_to my_bookings_path, status: :see_other
  end

  def my_bookings
    @bookings = Booking.where(user: current_user)
  end

  def host_bookings
    @host_bookings = current_user.host_bookings
  end

  def host_booking
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def params_booking
    params.require(:booking).permit(:start_date, :end_date, :status, :user_id, :character_id)
  end

  def find_host_character
    @host_characters = Character.where(user: current_user)
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: %i[show edit update destroy]

  def index
    @characters = Character.all

    if params[:query].nil?
      @characters = Character.all
    else
      @characters = Character.search_by_name_and_description(params[:query])
    end
  end

  def show
    @booking = Booking.new
    @marker = {
        lat: @character.latitude,
        lng: @character.longitude,
        # info_window: render_to_string(partial: 'info_window', locals: { character: @character }),
        image_url: helpers.asset_url("marker.png")
      }
  end

  def new
    @character = Character.new
  end

  def create
    @character = Character.new(character_params)
    @character.user = current_user

    if @character.save
      redirect_to @character, notice: 'Character was successfully created!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @character.photos.attach(params[:photos])
    @character.save
  end

  def update
    # raise
    if @character.update(character_params)
      redirect_to character_path(@character), notice: "Character was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @character.destroy
    redirect_to my_characters_path, status: :see_other
  end

  def my_characters
    @characters = Character.where(user: current_user)
  end

  private

  def set_character
    @character = Character.find(params[:id])
  end

  def character_params
    params.require(:character).permit(:name, :description, :price, :category, :user_id, :address, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class="container pt-5" style="width: 900px;">
  <div class="border rounded p-5">
  <h1 class="mb-4"><strong>Your booking details</strong></h1>

  <div class="d-flex mb-4">
    <%= cl_image_tag @booking.character.photos.all.first.key, :gravity=>"face", :height=>100, :width=>100, :crop=>"thumb", class: "rounded-4" %>
    <div>
      <h4 class="px-4 pt-3"><%= @booking.character.name %></h4>
      <p class="px-4"><%= @booking.character.address %></p>
    </div>
  </div>

  <h4><strong>Dates</strong></h4>
    <p class="mb-3"><%= @booking.start_date.strftime("%b.%d") %> - <%= @booking.end_date.strftime("%d") %></p>
  <div class="border-bottom"></div>
    <h4 class="mt-3"><strong>Price details</strong></h4>
  <div class="d-flex justify-content-between">
    <p>$ <%= @booking.character.price %> x <%= (@booking.end_date - @booking.start_date + 1).to_i %> day</p>
    <p>$ <%= @booking.character.price.to_i * (@booking.end_date - @booking.start_date + 1).to_i %></p>
  </div>
  <div class="d-flex justify-content-between">
    <p>Delivery fee</p>
    <p>$ 10</p>
  </div>
  <div class="border-bottom mb-3"></div>
    <div class="d-flex justify-content-between">
      <p><strong>Total(CAD)</strong></p>
      <p>$ <%= @booking.character.price.to_i * (@booking.end_date - @booking.start_date + 1).to_i + 10 %></p>
    </div>
  <div class="border-bottom"></div>
  <p class="mt-2"><small>Your character may charge an additional fee for emotional damage.</small></p>
  <%= link_to 'Cancel', delete_booking_path(@booking), class: "btn btn-primary w-100 mt-4", data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to cancel?' }%>
  </div>
</div>

app/views/bookings/host_bookings.html.erb
<div class="container">
  <h1>Manage Bookings</h1>

  <div class="cards">
    <% @host_bookings.each do |booking| %>
      <div class="card-product" style="height: 200px; display: inline-block;">
        <div class="d-flex justify-content-around">
          <img id="img-card-host" src="<%= cl_image_path booking.character.photos.all.first.nil? ? '' : booking.character.photos.all.first.key, height: 300, width: 400, crop: :fill %>" class="card-img-top" alt="...">
          <div class="card-product-infos pb-2">
            <h2 class="host-link"><%= booking.character.name %></h2>
            <p><%= booking.start_date.strftime("%b.%d") %> - <%= booking.end_date.strftime("%b.%d") %></p>
            <p>Price: <%= booking.character.price %>$</p>
            <p>Status: <strong><%= booking.status %></strong></p>
            <div class="status d-flex align-items-start">
                <button id="btn-confirm" class="btn"><%= link_to "Confirm", edit_status_path(booking, 1), data: { 'turbo-method': :patch }%></button>
                <button id="btn-deny"class="btn"><%= link_to "Deny", edit_status_path(booking, 2), data: { 'turbo-method': :patch }%></button>
            </div>
          </div>
        </div>
        <div class="">
          <p class="booked-status">Booked by: <%= booking.user.email %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/my_bookings.html.erb
<div class="container">
  <h1>My Bookings</h1>

  <div class="cards">
    <% @bookings.each do |booking| %>
      <div class="card-product">
        <img src="<%= cl_image_path booking.character.photos.all.first.nil? ? '' : booking.character.photos.all.first.key, height: 300, width: 400, crop: :fill %>" class="card-img-top img-fluid" alt="...">
        <div class="card-product-infos">
          <h2><%= link_to booking.character.name, edit_booking_path(booking), class: "index-link" %></h2>
          <p><%= booking.start_date.strftime("%b.%d") %> - <%= booking.end_date.strftime("%b.%d") %></p>
          <p>This booking is <strong><%= booking.status %></strong></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container pt-5" style="width: 900px;">
  <div class="border rounded p-5">
  <h1 class="mb-4"><strong>Your booking details</strong></h1>

  <div class="d-flex mb-4">
    <%= cl_image_tag @booking.character.photos.all.first.key, :gravity=>"face", :height=>100, :width=>100, :crop=>"thumb", class: "rounded-4" %>
    <div>
      <h4 class="px-4 pt-3"><%= @booking.character.name %></h4>
      <p class="px-4"><%= @booking.character.address %></p>
    </div>
  </div>

  <h4><strong>Dates</strong></h4>
    <p class="mb-3"><%= @booking.start_date.strftime("%b.%d") %> - <%= @booking.end_date.strftime("%d") %></p>
  <div class="border-bottom"></div>
    <h4 class="mt-3"><strong>Price details</strong></h4>
  <div class="d-flex justify-content-between">
    <p>$ <%= @booking.character.price %> x <%= (@booking.end_date - @booking.start_date + 1).to_i %> day</p>
    <p>$ <%= @booking.character.price.to_i * (@booking.end_date - @booking.start_date + 1).to_i %></p>
  </div>
  <div class="d-flex justify-content-between">
    <p>Delivery fee</p>
    <p>$ 10</p>
  </div>
  <div class="border-bottom mb-3"></div>
    <div class="d-flex justify-content-between">
      <p><strong>Total(CAD)</strong></p>
      <p>$ <%= @booking.character.price.to_i * (@booking.end_date - @booking.start_date + 1).to_i + 10 %></p>
    </div>
  <div class="border-bottom"></div>
  <p class="mt-2"><small>Your character may charge an additional fee for emotional damage.</small></p>

  <%= link_to "Request", my_bookings_path, class: "btn btn-primary w-100 mt-4" %>
  </div>
</div>

app/views/characters/_info_window.html.erb
<div class="container">
  <h2><%= character.name %></h2>
  <p><%= character.address %></p>
</div>

app/views/characters/edit.html.erb
<div class="container pt-5" style="width: 900px;">
  <div class="border rounded p-3">
  <%= simple_form_for @character do |f| %>
    <div class="mb-3">
      <%= f.label :name, "Name", class: "form-label" %>
      <%= f.input :name, label: false, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :description, "Description", class: "form-label" %>
      <%= f.input :description, label: false, class: "form-control", as: :text %>
    </div>
    <div class="mb-3">
      <%= f.label :description, "Price", class: "form-label" %>
      <%= f.input :price, label: false, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :category, "Select a category", class: "form-label" %>
      <%= f.input :category, collection: %w[Animation Animal Christmas Comedy Game Horror Superhero Princess Other], class: "form-select", html5: true, label: false %>
    </div>
    <div class="mb-3">
      <%= f.label :address, "Address", class: "form-label" %>
      <%= f.input :address, label: false, class: "form-control" %>
    </div>
    <%#= f.input :photos, as: :file, input_html: { multiple: true }, class: "form-control" %>
    <%= f.submit "Edit", class: "btn btn-primary w-100 py-2" %>
  <% end %>
</div>

app/views/characters/index.html.erb
<div class="container">
  <%= form_with url: characters_path, method: :get, class: "d-flex my-1 search" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a character"
    %>
    <%= submit_tag "Search", class: "btn btn-warning" %>
  <% end %>

  <div class="cards">
    <% @characters.each do |character| %>
      <sl-card class="card-overview">
        <img
          slot="image"
          src="<%= cl_image_path character.photos.all.first.nil? ? '' : character.photos.all.first.key, height: 300, width: 350, crop: :fill %>"
          alt=""
        />
        <h2><%= link_to character.name, character_path(character), class: "index-link" %></h2>

        <div slot="footer">
          <%= link_to "Book me!", character_path(character), class: "sl-button pill warning", id: "book-me" %>
          <h5 class="card-trip-pricing">$<%= character.price %>/day</h5>
        </div>
      </sl-card>
    <% end %>
  </div>
</div>

app/views/characters/my_characters.html.erb
<div class="container">
  <h1>Manage Characters</h1>

  <div class="cards">
    <% @characters.each do |character| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path character.photos.all.first.nil? ? 'https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg' : character.photos.all.first.key, height: 300, width: 400, crop: :fill, gravity: :auto %>')">
        <%= link_to character.name, character_path(character), class: "my-character" %>
      </div>
    <% end %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))"><%= link_to '+', new_character_path %></div>
  </div>
</div>

app/views/characters/new.html.erb
<div class="container pt-5" style="width: 900px;">
  <div class="border rounded p-3">
  <%= simple_form_for @character do |f| %>
    <div class="mb-3">
      <%= f.label :name, "Name", class: "form-label" %>
      <%= f.input :name, label: false, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :description, "Description", class: "form-label" %>
      <%= f.input :description, label: false, class: "form-control", as: :text %>
    </div>
    <div class="mb-3">
      <%= f.label :description, "Price", class: "form-label" %>
      <%= f.input :price, label: false, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :category, "Select a category", class: "form-label" %>
      <%= f.input :category, collection: %w[Animation Animal Christmas Comedy Game Horror Superhero Princess Other], class: "form-select", html5: true, label: false %>
    </div>
    <div class="mb-3">
      <%= f.label :address, "Address", class: "form-label" %>
      <%= f.input :address, label: false, class: "form-control" %>
    </div>
    <%= f.input :photos, as: :file, input_html: { multiple: true }, class: "form-control" %>
    <%= f.submit "Add a new character", class: "btn btn-primary w-100 py-2" %>
  <% end %>
</div>

app/views/characters/show.html.erb
<div class="container">
  <div class="m-0 d-flex align-items-center justify-content-between">
    <h1 class="align-self-end"><strong><%= @character.name %></strong></h1>
    <h4 class="align-self-end"><strong>$<%= @character.price %></strong> / day</h4>
  </div>
    <%= icon('fa-solid', 'location-dot')%> <%= @character.address %>

  <div class="row">
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner rounded my-3">
        <% @character.photos.each_with_index do |photo, index| %>
          <div class="carousel-item<%= " active" if index.zero? %>">
            <img class="d-block" src="<%= cl_image_path photo.key, :gravity=>"auto", :height=>400, :width=>1200, :crop=>"fill" %>" alt="">
          </div>
        <% end %>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>

    <div class="col-12 col-lg-8">
      <div class="rounded p-3" style="height: 300px;">
        <span class="badge text-bg-warning"><%= @character.category %></span>
        <h3 class="py-3"><%= @character.description %></h3>
      </div>
    </div>

  <% unless @character.user == current_user %>
    <div class="col-12 col-lg-4 mb-3">
      <div class="border rounded p-3" style="height: 300px;">
        <%= simple_form_for([@character, @booking]) do |f| %>
        <div class="form-group py-3">
          <%= f.label :start_date, "From" %>
          <%= f.input :start_date, class: "form-control", html5: true, label: false %>
        </div>
        <div class="form-group pb-4">
          <%= f.label :end_date, "To" %>
          <%= f.input :end_date, class: "form-control", html5: true, label: false %>
        </div>
        <%= f.submit "Book now", class: "btn btn-primary w-100 py-2" %>
        <% end %>
      </div>
    </div>
  <% end %>

  <% if @character.user == current_user %>
    <div class="col-12 col-lg-4 mb-3">
      <div class="rounded p-3" style="height: 300px;">
          <%= link_to 'Edit', edit_character_path(@character), class: "btn btn-primary w-100 mb-3" %>
          <%= link_to 'Delete', delete_character_path(@character), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-primary w-100" %>
      </div>
    </div>
  <% end %>


  <div class="col-12">
    <div class="border rounded"
      style="width: 100%; height: 400px;"
      data-controller="map"
      data-map-marker-value="<%= @marker.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VarChar</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.0.0-beta.83/dist/themes/light.css" />
    <script type="module" src="https://cdn.jsdelivr.net/npm/@shoelace-style/shoelace@2.0.0-beta.83/dist/shoelace.js"></script>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="margin-bottom-push-down"><%= render 'shared/navbar' %></div>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="home-container" >
  <div class="banner d-flex justify-content-center align-items-center">
    <div id="all_img_banner" class="image col-9 banner-image" onload="document.div.style.opacity='1'">
      <%= image_tag "home-page-body.jpg", id: "home-page-banner"  %>
      <%= image_tag "home-page-lunette.png", id: "home-page-banner-lunette"  %>
      <%= image_tag "home-page-goute.png", id: "home-page-banner-goute"  %>
      <%= image_tag "home-page-deco.png", id: "home-page-banner-deco"  %>
      <%= image_tag "home-page-tatoo.png", id: "home-page-banner-tatoo"  %>
    </div>
    <div class="banner-text"><p>Be who you want to be... <br> or <strong>RENT IT</strong>!</p></div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar fixed-top bg-white">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "4u.png" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        <%# <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Offcanvas</h5> %>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item active">
            <%= link_to "All Characters", "/characters", class: "nav-link" %>
          </li>
        <% if user_signed_in? %>
          <li class="nav-item active border-bottom pb-3">
            <%= link_to "My Bookings", "/my-bookings", class: "nav-link" %>
          </li>
          <li class="nav-item active pt-3">
            <%= link_to "Manage Characters", "/my-characters", class: "nav-link" %>
          </li>
          <li class="nav-item active border-bottom pb-3">
            <%= link_to "Manage Bookings", "/host-bookings", class: "nav-link" %>
          </li>
          <li class="nav-item active pt-3 text-center">
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete} %>
          </li>
        <% else %>
          <li class="nav-item active border-top">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        </ul>
        <% end %>
      </div>
    </div>
  </div>
</nav>